robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_right
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/ttyUSB1
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [4.712, 4.712, 3.142, 6.283, 1.571, 0.000]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 125.13203125, 83.33203125]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
hz: 30
max_steps: 1000