robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/ttyUSB0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [1.571, 1.571, 3.142, 1.571, 4.712, 1.571]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 233.5890625, 191.7890625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
hz: 30
max_steps: 1000