robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_left
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/ttyUSB0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [1, 2, 3, 4, 5, 6]
    joint_offsets: [4.71239, 4.71239, 3.14159, 6.28319, 1.5708, 0.0]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [7, 22.4140625, 81.9140625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
hz: 30
max_steps: 1000
